project:
  type: book

book:
  title: 'iHuman Lab Research Manual'
  author: 'Hemanth Manjunatha'
  date: today
  sidebar:
    logo: images/logo.png
    search: true
  page-navigation: true
  chapters:
    - index.qmd
    - introduction.qmd
    - part: writing_practices/general_principles.qmd
      chapters:
        - writing_practices/writing_articles.qmd
        - writing_practices/making_diagrams.qmd
        - writing_practices/making_presentations.qmd
        - writing_practices/making_posters.qmd
    - part: coding_practices/general_practices.qmd
      chapters:
        - coding_practices/development_setup.qmd
        - coding_practices/clean_code.qmd
        - coding_practices/code_decoupling.qmd
        - coding_practices/code_testing.qmd
        - coding_practices/code_documentation.qmd
        - coding_practices/project_structure.qmd
    - python_resources.qmd
    - bci_resources.qmd
    - eeg_resources.qmd
    - ros_resources.qmd
    - lab_resources.qmd
    - checklist_and_signature.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: dracula
  pdf:
    documentclass: scrreprt
