# Welcome {.unnumbered}


We are glad that you have decided to join **`I`**ntelligent **`Hu`**man-**`Ma`**chine **`N`**exus Lab (iHuman Lab)! We are really excited to have you as a part of our team and we will do what we can to make sure that you have a great time in our lab. We hope you will learn a lot about human and machines, and neuroscience, develop new and useful skills (coding, data analysis, writing papers, giving talks), make new friends, and have a great deal of fun throughout the whole process!!

This lab manual is crafted as your essential companion, designed to acquaint you with our lab’s standard workflow. Within these pages, you will find detailed explanations writing and coding practices, learning resources for Python, BCI, and physiological data processing. These workflows ensure smooth integration into our research.

## Acknowledgment {.unnumbered}

This lab manual draws inspiration from various sources, and in some sections, content has been adapted or reproduced from these sources. We acknowledge the following works for their influence:

[Context Dynamics Lab](https://`GitHub`.com/ContextLab/lab-manual), [The Memory Modulation Lab](https://bpb-us-w2.wpmucdn.com/sites.gatech.edu/dist/2/1249/files/2023/04/Maureen-Ritchey-Boston-College.pdf), [Aly Lab](https://bpb-us-w2.wpmucdn.com/sites.gatech.edu/dist/2/1249/files/2023/04/aly-lab-manual.pdf), [Peelle Lab](https://sites.gatech.edu/cdi/files/2023/04/Jonathan-Peelle-Washington-University-in-Saint-Louis.pdf), [Ritchey Lab](https://sites.gatech.edu/cdi/files/2023/04/Maureen-Ritchey-Boston-College.pdf), [Kemp Lab](https://sites.gatech.edu/cdi/files/2023/04/Melissa-Kemp-Georgia-Tech-Emory-University.pdf)

This lab manual is licensed under the Creative Commons Attribution 4.0 International License. You are free to share, adapt, and redistribute the material in any medium or format, provided appropriate credit is given to the original authors and the source is properly cited.



